version: "3.8"

services:
  consul:
    image: hashicorp/consul:1.20
    container_name: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
  
  service-express-a:
    image: service-express-a
    container_name: service-express-a
    build:
      context: ./services/service-a
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - EXPRESS_HOST=service-express-a
      - EXPRESS_PORT=3000
      - CONSULT_HOST=consul
      - CONSULT_PORT=8500
    depends_on:
      - consul

  service-express-b:
    image: service-express-b
    container_name: service-express-b
    build:
      context: ./services/service-b
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - EXPRESS_HOST=service-express-b
      - EXPRESS_PORT=4000
      - CONSULT_HOST=consul
      - CONSULT_PORT=8500
    depends_on:
      - consul