version: "3.8"

services:
  consul:
    image: hashicorp/consul:1.20
    container_name: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
  
  service-express:
    image: service-express
    container_name: service-express
    build:
      context: ./services/service-a
      dockerfile: Dockerfile
    environment:
      - EXPRESS_HOST=service-express
      - EXPRESS_PORT=3000
      - CONSULT_HOST=consul
      - CONSULT_PORT=8500
    ports:
      - "3000:3000"
    depends_on:
      - consul

  service-rocket:
    image: service-rocket
    container_name: service-rocket
    build:
      context: ./services/service-b
      dockerfile: Dockerfile
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - consul